id: A622C3CC1
title: Prayer of Aspiration Towards Sukhāvatī
type: translation
pechas:
- I5C41A6AF
- IDD6C3494
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:47:40.345957
  last_modified_at: 2023-01-04 12:47:40.345989
  collections:
  - Katok Situ Chökyi Gyatso Series
  - Works of Tibetan Masters
alignment_to_base:
  I5C41A6AF/D688: 813C
  IDD6C3494/81B7: 813C
